spring:
  application:
    name: consumer-user
server:
  port: 8200
eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:            #指定注册中心的地址的   非常重要
      defaultZone : http://localhost:8761/eureka
