server:
  port: 8003
spring:
  application:
    name: privoder-ticket

eureka:
  instance:
    prefer-ip-address: true   #注册服务的时候  使用 ip地址来注册
  client:
    service-url:            #指定注册中心的地址的   非常重要
      defaultZone : http://45.123.197.14:8761/eureka
